name = "Thunder"
author = "https://github.com/rooneyj9005"
version = "0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c8156e2a6fd92288cbb910b5df5a376e0dbd79c4fad5e2e2c9a9cc963309304"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
