name = "Thunder"
author = "https://github.com/rooneyj9005"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4f74736cac6cb14bdd219543204e8d478f1eca513438256260b5d1987a9ea20"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
