name = "Thunder"
author = "https://github.com/rooneyj9005"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38f0f72a61a90da9dba1cd45022ea0a433a19e2a68dd6769697076e538927df4"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
